---
repos:
  - hooks:
      - id: autoflake
        exclude: cognite/client/_proto/
        args:
          - --remove-all-unused-imports
          - --in-place
    repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
  - hooks:
      - id: isort
        exclude: cognite/client/_proto/
        args:
          - --profile
          - black
          - --line-length
          - '120'
          - -m
          - '3'
          - --tc
          - --skip-glob
          - ^((?!py$).)*$
          - --float-to-top
    repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
  - hooks:
      - id: black
        exclude: cognite/client/_proto/
        args:
          - --line-length
          - '120'
          - --target-version
          - py37
          - --include
          - \.py$
    repo: https://github.com/psf/black
    rev: 22.3.0
  - hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy cognite --non-interactive --install-types
        language: system
        files: ^.*.(py|pyi)$
        pass_filenames: false
    repo: local
  - hooks:
      - id: flake8
        exclude: cognite/client/_proto/
# TODO: add this too
#            additional_dependencies:
#              - flake8-builtins
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
  - hooks:
      - id: version-match-check
        name: version-match-check
        entry: poetry run python scripts/check_version_match.py
        language: system
        pass_filenames: false
    repo: local
