---
repos:
  # We use a local ruff hook so that the ruff version matches the one in dev-dependencies
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: python
        types_or: [python, pyi, jupyter]
        require_serial: true
        entry: ruff check
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --force-exclude
      - id: ruff-format
        name: ruff format
        language: python
        types_or: [python, pyi, jupyter]
        require_serial: true
        entry: ruff format
        args:
          - --force-exclude

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: debug-statements
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: mypy
        name: mypy
      # Eventually we want to run mypy on the whole test code base. But for now we only enable it for data modeling tests.
        entry: |
          poetry run dmypy run -- cognite 
          
          tests/tests_unit/test_data_classes
          tests/tests_unit/test_utils
          tests/tests_unit/test_api_client.py
          tests/tests_unit/test_base.py
          tests/tests_unit/test_cognite_client.py
          tests/tests_unit/test_config.py
          tests/tests_unit/test_credential_providers.py
          tests/tests_unit/test_docstring_examples.py
          tests/tests_unit/test_exceptions.py
          
          tests/tests_unit/test_api/test_assets.py
          tests/tests_unit/test_api/test_events.py
          tests/tests_unit/test_api/test_datapoints.py
          tests/tests_unit/test_api/test_data_sets.py
          tests/tests_unit/test_api/test_geospatial.py
          tests/tests_unit/test_api/test_raw.py
          tests/tests_unit/test_api/test_time_series.py
          tests/tests_unit/test_api/test_3d.py
          tests/tests_unit/test_api/test_vision_extract.py
          tests/tests_unit/test_api/test_transformations.py
          
          tests/tests_integration/test_api/test_data_modeling
          tests/tests_integration/test_api/test_datapoints.py
          tests/tests_integration/test_api/test_assets.py
          tests/tests_integration/test_api/test_events.py
          tests/tests_integration/test_api/test_workflows.py
          tests/tests_integration/test_api/test_raw.py
          tests/tests_integration/test_api/test_transformations

          tests/tests_integration/test_api/test_simulators
          tests/tests_integration/test_api/test_principals.py
          tests/tests_unit/test_api/test_simulators
        files: ^.*.(py|pyi)$
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: custom-checks
        name: custom repo checks
        entry: poetry run python scripts/run_checks.py
        files: ^cognite/.*.(py|pyi)$
        language: system
        pass_filenames: true
        require_serial: true  # avoid possible race conditions

  - repo: https://github.com/jsh9/pydoclint  # Run after 'custom-checks' as these may auto-fix
    rev: 0.8.3
    hooks:
      - id: pydoclint
        require_serial: true  # Spammy in run-all scenarios (more than fast enough already)
        args:
          - --style=google
          - --exclude=tests/|scripts/
          - --quiet  # otherwise prints all checked files that are ok...
          - --skip-checking-raises=true
          - --check-class-attributes=false
