---
repos:
  # We use a local ruff hook so that the ruff version matches the one in dev-dependencies
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: python
        types_or: [python, pyi, jupyter]
        require_serial: true
        entry: ruff check
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --force-exclude
      - id: ruff-format
        name: ruff format
        language: python
        types_or: [python, pyi, jupyter]
        require_serial: true
        entry: ruff format
        args:
          - --force-exclude

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: debug-statements
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run dmypy run -- cognite tests
        files: ^.*.(py|pyi)$
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: custom-checks
        name: custom repo checks
        entry: poetry run python scripts/run_checks.py
        files: ^cognite/.*.(py|pyi)$
        language: system
        pass_filenames: true
        require_serial: true  # avoid possible race conditions

  - repo: https://github.com/jsh9/pydoclint  # Run after 'custom-checks' as these may auto-fix
    rev: 0.8.1
    hooks:
      - id: pydoclint
        require_serial: true  # Spammy in run-all scenarios (more than fast enough already)
        args:
          - --style=google
          - --exclude=tests/|scripts/
          - --quiet  # otherwise prints all checked files that are ok...
          - --skip-checking-raises=true
          - --check-class-attributes=false
